services:
  anythingllm:
    image: mintplexlabs/anythingllm
    container_name: anythingllm
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    volumes:
      - /mnt/volume-syd1-05/anythingllm:/app/server/storage
    environment:
      - STORAGE_DIR=/app/server/storage
    networks:
      - caddy-net

networks:
  caddy-net:
